// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SmartwatchSC01

#include "../ui.h"

void ui_Config_screen_init(void)
{
    ui_Config = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_7 = lv_img_create(ui_Config);
    lv_img_set_src(ui_bg_7, &ui_img_fondmulticolor_png);
    lv_obj_set_width(ui_bg_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button_down6 = ui_buttondown_create(ui_Config);
    lv_obj_set_x(ui_button_down6, 199);
    lv_obj_set_y(ui_button_down6, 121);

    lv_img_set_src(ui_comp_get_child(ui_button_down6, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    ui_Container1 = lv_obj_create(ui_Config);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 442);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_x(ui_Container1, 4);
    lv_obj_set_y(ui_Container1, -135);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Luminosite = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_Luminosite, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Luminosite) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Luminosite, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Luminosite, 346);
    lv_obj_set_height(ui_Luminosite, 20);
    lv_obj_set_x(ui_Luminosite, 48);
    lv_obj_set_y(ui_Luminosite, 4);
    lv_obj_set_align(ui_Luminosite, LV_ALIGN_CENTER);

    lv_obj_set_style_border_color(ui_Luminosite, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Luminosite, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelLuminosite = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelLuminosite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLuminosite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLuminosite, -178);
    lv_obj_set_y(ui_LabelLuminosite, 7);
    lv_obj_set_align(ui_LabelLuminosite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLuminosite, "Luminosite");

    ui_ssid = lv_dropdown_create(ui_Config);
    lv_dropdown_set_options(ui_ssid, "SSID 1\nSSID 2\nSSID 3");
    lv_obj_set_width(ui_ssid, 360);
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssid, -35);
    lv_obj_set_y(ui_ssid, -100);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ssid, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_password = lv_textarea_create(ui_Config);
    lv_obj_set_width(ui_password, 438);
    lv_obj_set_height(ui_password, 60);
    lv_obj_set_x(ui_password, 4);
    lv_obj_set_y(ui_password, -53);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_password, "Mot de passe wifi");



    ui_bpenregistrer = lv_btn_create(ui_Config);
    lv_obj_set_width(ui_bpenregistrer, 168);
    lv_obj_set_height(ui_bpenregistrer, 24);
    lv_obj_set_x(ui_bpenregistrer, 2);
    lv_obj_set_y(ui_bpenregistrer, 128);
    lv_obj_set_align(ui_bpenregistrer, LV_ALIGN_CENTER);
    lv_obj_set_style_clip_corner(ui_bpenregistrer, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bpenregistrer, lv_color_hex(0x151313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bpenregistrer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_bpenregistrer, lv_color_hex(0x292828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_bpenregistrer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_bpenregistrer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_bpenregistrer, lv_color_hex(0x6F6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_bpenregistrer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_bpenregistrer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_bpenregistrer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_bpenregistrer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_bpenregistrer, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_bpenregistrer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_bpenregistrer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpenregistrer, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bpenregistrer, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_bpenregistrer, true, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_bpenregistrer, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_bpenregistrer, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_x(ui_bpenregistrer, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_y(ui_bpenregistrer, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_bpenregistrer, lv_color_hex(0x090101), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_bpenregistrer, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_letter_space(ui_bpenregistrer, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_line_space(ui_bpenregistrer, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_decor(ui_bpenregistrer, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_font(ui_bpenregistrer, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_bpenregistrer);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Enregistrer");

    ui_Keyboard1 = lv_keyboard_create(ui_Config);
    lv_obj_set_width(ui_Keyboard1, 442);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 4);
    lv_obj_set_y(ui_Keyboard1, 42);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_button_down6, ui_event_button_down6_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Luminosite, ui_event_Luminosite, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_password, ui_event_password, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bpenregistrer, ui_event_bpenregistrer, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_password);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config, ui_event_Config, LV_EVENT_ALL, NULL);

}
