// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SmartwatchSC01

#include "../ui.h"

void ui_Conso_EDF_screen_init(void)
{
    ui_Conso_EDF = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Conso_EDF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Conso_EDF, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Conso_EDF, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_1 = lv_img_create(ui_Conso_EDF);
    lv_img_set_src(ui_bg_1, &ui_img_fondmulticolor1_png);
    lv_obj_set_width(ui_bg_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bg_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bg_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Edf = lv_chart_create(ui_Conso_EDF);
    lv_obj_set_width(ui_Edf, 410);
    lv_obj_set_height(ui_Edf, 288);
    lv_obj_set_x(ui_Edf, 3);
    lv_obj_set_y(ui_Edf, -7);
    lv_obj_set_align(ui_Edf, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Edf, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Edf, 48);
    lv_chart_set_div_line_count(ui_Edf, 2, 4);
    lv_chart_set_axis_tick(ui_Edf, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Edf, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 5);
    lv_chart_set_axis_tick(ui_Edf, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_Edf_series_1 = lv_chart_add_series(ui_Edf, lv_color_hex(0x8DE74F), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Edf_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Edf, ui_Edf_series_1, ui_Edf_series_1_array);
    lv_chart_series_t * ui_Edf_series_2 = lv_chart_add_series(ui_Edf, lv_color_hex(0x140DEE), LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Edf_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 20, 30 };
    lv_chart_set_ext_y_array(ui_Edf, ui_Edf_series_2, ui_Edf_series_2_array);



    ui_ConsoClic = lv_label_create(ui_Edf);
    lv_obj_set_width(ui_ConsoClic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsoClic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_ConsoClic, 12);
    lv_obj_set_x(ui_ConsoClic, lv_pct(44));
    lv_label_set_text(ui_ConsoClic, "27");
    lv_obj_set_style_text_color(ui_ConsoClic, lv_color_hex(0x080808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsoClic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsoClic, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_down = ui_buttondown_create(ui_Conso_EDF);
    lv_obj_set_x(ui_button_down, 208);
    lv_obj_set_y(ui_button_down, 124);
    lv_obj_set_style_blend_mode(ui_button_down, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_button_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_img_set_src(ui_comp_get_child(ui_button_down, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    lv_obj_add_event_cb(ui_Edf, ui_event_Edf, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_down, ui_event_button_down_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Conso_EDF, ui_event_Conso_EDF, LV_EVENT_ALL, NULL);

}
