// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SmartwatchSC01

#include "../ui.h"

void ui_Moto_screen_init(void)
{
    ui_Moto = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Moto, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Moto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Moto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Moto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_6 = lv_img_create(ui_Moto);
    lv_img_set_src(ui_bg_6, &ui_img_fondmulticolor1_png);
    lv_obj_set_width(ui_bg_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bg_6, 2);
    lv_obj_set_y(ui_bg_6, -1);
    lv_obj_set_align(ui_bg_6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bg_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bg_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BgZero = lv_img_create(ui_Moto);
    lv_img_set_src(ui_BgZero, &ui_img_zerotrans1_png);
    lv_obj_set_width(ui_BgZero, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BgZero, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BgZero, 61);
    lv_obj_set_y(ui_BgZero, -20);
    lv_obj_set_align(ui_BgZero, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BgZero, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BgZero, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_priseCharge = lv_img_create(ui_Moto);
    lv_img_set_src(ui_priseCharge, &ui_img_prise100trans_png);
    lv_obj_set_width(ui_priseCharge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_priseCharge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_priseCharge, 2);
    lv_obj_set_y(ui_priseCharge, -65);
    lv_obj_set_align(ui_priseCharge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_priseCharge, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_pivot(ui_priseCharge, 50, 50);
    lv_img_set_angle(ui_priseCharge, 1000);
    lv_img_set_zoom(ui_priseCharge, 230);
    lv_obj_set_style_blend_mode(ui_priseCharge, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_priseCharge, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_priseCharge, lv_color_hex(0xE50F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_priseCharge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flashAlim = lv_img_create(ui_Moto);
    lv_img_set_src(ui_flashAlim, &ui_img_flash_png);
    lv_obj_set_width(ui_flashAlim, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flashAlim, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_flashAlim, 14);
    lv_obj_set_y(ui_flashAlim, -86);
    lv_obj_set_align(ui_flashAlim, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_flashAlim, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_pivot(ui_flashAlim, 6, 9);
    lv_img_set_angle(ui_flashAlim, -500);
    lv_img_set_zoom(ui_flashAlim, 320);
    lv_obj_set_style_blend_mode(ui_flashAlim, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_flashAlim, 230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_down5 = ui_buttondown_create(ui_Moto);
    lv_obj_set_x(ui_button_down5, 202);
    lv_obj_set_y(ui_button_down5, 121);

    lv_img_set_src(ui_comp_get_child(ui_button_down5, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    lv_obj_set_style_blend_mode(ui_comp_get_child(ui_button_down5, UI_COMP_BUTTONDOWN_LINE), LV_BLEND_MODE_NORMAL,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_comp_get_child(ui_button_down5, UI_COMP_BUTTONDOWN_LINE), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelCharge = lv_label_create(ui_Moto);
    lv_obj_set_width(ui_labelCharge, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_labelCharge, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_labelCharge, 72);
    lv_obj_set_y(ui_labelCharge, -24);
    lv_obj_set_align(ui_labelCharge, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCharge, "Charge");
    lv_obj_set_style_text_color(ui_labelCharge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelCharge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelCharge, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_labelCharge, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_labelCharge, 130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jaugeCharge1 = lv_arc_create(ui_Moto);
    lv_obj_set_width(ui_jaugeCharge1, 92);
    lv_obj_set_height(ui_jaugeCharge1, 88);
    lv_obj_set_x(ui_jaugeCharge1, 76);
    lv_obj_set_y(ui_jaugeCharge1, 30);
    lv_obj_set_align(ui_jaugeCharge1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_jaugeCharge1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_jaugeCharge1, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_value(ui_jaugeCharge1, 30);
    lv_obj_set_style_arc_color(ui_jaugeCharge1, lv_color_hex(0xDCFAD2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_jaugeCharge1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_jaugeCharge1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_jaugeCharge1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_jaugeCharge1, lv_color_hex(0x55D914), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_jaugeCharge1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_jaugeCharge1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_jaugeCharge1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_jaugeCharge1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ChargePCT2 = lv_label_create(ui_jaugeCharge1);
    lv_obj_set_width(ui_ChargePCT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargePCT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargePCT2, -9);
    lv_obj_set_y(ui_ChargePCT2, -3);
    lv_obj_set_align(ui_ChargePCT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargePCT2, "50");
    lv_obj_set_style_text_color(ui_ChargePCT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargePCT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargePCT2, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargePCT3 = lv_label_create(ui_jaugeCharge1);
    lv_obj_set_width(ui_ChargePCT3, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_ChargePCT3, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_ChargePCT3, 13);
    lv_obj_set_y(ui_ChargePCT3, -4);
    lv_obj_set_align(ui_ChargePCT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargePCT3, "%");
    lv_obj_clear_flag(ui_ChargePCT3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ChargePCT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargePCT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargePCT3, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enCharge = lv_spinner_create(ui_Moto, 1000, 90);
    lv_obj_set_width(ui_enCharge, 90);
    lv_obj_set_height(ui_enCharge, 90);
    lv_obj_set_x(ui_enCharge, 74);
    lv_obj_set_y(ui_enCharge, 29);
    lv_obj_set_align(ui_enCharge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_enCharge, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_enCharge, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_enCharge, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_enCharge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_enCharge, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_enCharge, lv_color_hex(0x52DA10), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_enCharge, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_enCharge, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_enCharge, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_analyseMoto = lv_textarea_create(ui_Moto);
    lv_obj_set_width(ui_analyseMoto, 338);
    lv_obj_set_height(ui_analyseMoto, 308);
    lv_obj_set_x(ui_analyseMoto, -65);
    lv_obj_set_y(ui_analyseMoto, -1);
    lv_obj_set_align(ui_analyseMoto, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_analyseMoto, "Bla bla bla\nposition : 6 sente du haras\n");
    lv_textarea_set_placeholder_text(ui_analyseMoto, "Placeholder...");
    lv_obj_set_style_text_color(ui_analyseMoto, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_analyseMoto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_analyseMoto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_analyseMoto, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_labelAutoRest = lv_label_create(ui_Moto);
    lv_obj_set_width(ui_labelAutoRest, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_labelAutoRest, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_labelAutoRest, 69);
    lv_obj_set_y(ui_labelAutoRest, 82);
    lv_obj_set_align(ui_labelAutoRest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelAutoRest, "--> 150Km");
    lv_obj_set_style_text_color(ui_labelAutoRest, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelAutoRest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelAutoRest, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button_down5, ui_event_button_down5_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jaugeCharge1, ui_event_jaugeCharge1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Moto, ui_event_Moto, LV_EVENT_ALL, NULL);

}
